name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: |
          nix develop -c bash -euxo pipefail -c 'npm ci'

      - name: Build
        run: |
          nix develop -c bash -euxo pipefail -c 'npm run build'

      - name: Upload dist artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Skip artifact upload (act)
        if: ${{ env.ACT }}
        run: echo "Skipping artifact upload under act local run"
