# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package (Nix)

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install Nix (for npm cli only)
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
        run: |
          set -euo pipefail
          nix develop --command bash -ceu 'npm publish --access public'
